### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by orbex**
Fixed 2 small typos

### CODE REVIEW

**Comment by BigOokie** [comment]
Thanks for picking this up. I will look over the pull request later today and merge.

**Comment by BigOokie** [comment]
Thx again. Merged and will close the issue

**Comment by orbex** [comment]
No problem, glad to help :)

**Comment by BigOokie** [comment]
I wrote most of this howto using a tool called CodeHub on my iPhone while on the train to work. I’m actually surprised there are not more issues. Lol.

Appreciate the feedback and input.

**Pull request merged**
